version: "3.8"
services:
    pdev:
        image: php:8.1.13-fpm-alpine3.16
        container_name: pdev
        restart: always
        tty: true
        volumes:
            - .:/var/www/html
        networks:
            - default

networks:
    default:
        name: gomore-network
        external: true
